# Use an official Python runtime as a parent image
# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir fastapi pydantic uvicorn nltk 

# Download nltk data
RUN python -m nltk.downloader punkt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["uvicorn", "data_preprocessing.main:app", "--host", "0.0.0.0", "--port", "2000"]
